import crypto from 'crypto';

// The secret key for signing OTP tokens. In a real app, this should be an environment variable.
const OTP_SECRET = process.env.OTP_SECRET || 'super-secret-cumita-otp-key-2026';

/**
 * Generate a stateless OTP token
 * @param otp The 6-character OTP code
 * @param expiresInMinutes How long the OTP is valid
 * @returns A base64 token containing the expiration and HMAC signature
 */
export function generateOTPToken(otp: string, expiresInMinutes: number = 5): string {
  const expiresAt = Date.now() + expiresInMinutes * 60 * 1000;
  
  // Create an HMAC of the OTP and the expiration time
  const hmac = crypto.createHmac('sha256', OTP_SECRET);
  hmac.update(`${otp}:${expiresAt}`);
  const signature = hmac.digest('hex');
  
  // Format: expiresAt:signature
  const payload = `${expiresAt}:${signature}`;
  
  // Encode in base64 to make it easy to pass around
  return Buffer.from(payload).toString('base64');
}

/**
 * Verify a stateless OTP token
 * @param otp The 6-character OTP code the user entered
 * @param token The base64 token generated by generateOTPToken
 * @returns boolean true if valid and not expired, false otherwise
 */
export function verifyOTPToken(otp: string, token: string): boolean {
  try {
    const decoded = Buffer.from(token, 'base64').toString('utf-8');
    const [expiresAtStr, signature] = decoded.split(':');
    
    if (!expiresAtStr || !signature) return false;
    
    const expiresAt = parseInt(expiresAtStr, 10);
    
    // Check expiration
    if (Date.now() > expiresAt) {
      return false; // Expired
    }
    
    // Recompute signature
    const hmac = crypto.createHmac('sha256', OTP_SECRET);
    hmac.update(`${otp}:${expiresAt}`);
    const expectedSignature = hmac.digest('hex');
    
    // Compare securely
    if (signature.length !== expectedSignature.length) return false;
    
    return crypto.timingSafeEqual(
      Buffer.from(signature, 'utf-8'),
      Buffer.from(expectedSignature, 'utf-8')
    );
  } catch (error) {
    return false;
  }
}

/**
 * Generates a random 6-character alphanumeric code
 */
export function generateRandomOTP(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // removed confusing chars like O,0,1,I
  let result = '';
  for (let i = 0; i < 6; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}
